/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-metal-warehouse-shelving-ccc250d7e54e4e4399ca3a8c2b477020
Title: Rusty Metal Warehouse Shelving
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import shelf from '../glbs/rusty_metal_warehouse_shelving.glb'

export default function Model(props) {
  const { nodes, materials } = useGLTF(shelf)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials.cardboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.tape}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.material}
        />
        <lineSegments geometry={nodes.Material2_3.geometry} material={materials.edge_color000255} />
        <lineSegments
          geometry={nodes.Material2_4.geometry}
          material={materials.edge_color19921133255}
        />
      </group>
    </group>
  )
}

useGLTF.preload(shelf)